build:
	CARGO_TARGET_DIR=target cargo build --profile=release_activity

serve:
	obelisk server run --deployment obelisk-local.toml

verify-local:
	obelisk server verify --ignore-missing-env-vars --deployment obelisk-local.toml

verify-oci:
	obelisk server verify --ignore-missing-env-vars --deployment obelisk-oci.toml

push tag:
	(../../scripts/push-components.sh {{ tag }})
