# GitHub
build:
	cargo build --profile=release_activity
verify-local: build
	obelisk server verify --ignore-missing-env-vars -c obelisk-local.toml
verify-oci:
	obelisk server verify --ignore-missing-env-vars -c obelisk-oci.toml
push tag: build
	(../../scripts/push-components.sh {{ tag }})
