[[activity_wasm]]
name = "activity_http_generic"
location = "target/wasm32-wasip2/release_activity/activity_http_generic.wasm"
exec.lock_expiry.seconds = 5
[[activity_wasm.allowed_host]]
pattern = "*"
methods = "*"
