[[activity_wasm]]
name = "activity_postmark_email"
location = "oci://docker.io/getobelisk/components_postmark_activity_postmark_email:2026-07-13@sha256:b0704585d94275b6e23661274be4a0bbf7231c37d22223399046e3f172b2d49c"
exec.lock_expiry.seconds = 30
env_vars = [{key="POSTMARK_API_URL", value="${POSTMARK_API_URL:-https://api.postmarkapp.com/email}"}]
[[activity_wasm.allowed_host]]
pattern = "${POSTMARK_API_DOMAIN:-api.postmarkapp.com}"
methods = ["POST"]
[activity_wasm.allowed_host.secrets]
env_vars = ["POSTMARK_SERVER_TOKEN"]
replace_in = ["headers"]
