[[activity_wasm]]
name = "activity_postmark_email"
location = "oci://docker.io/getobelisk/components_postmark_activity_postmark_email:2026-04-08@sha256:e5e2f42b2babca1accb4722a3443577a4f97753d0d2ede42e2005a2416601f7a"
exec.lock_expiry.seconds = 30
env_vars = [{key="POSTMARK_API_URL", value="${POSTMARK_API_URL:-https://api.postmarkapp.com/email}"}]
[[activity_wasm.allowed_host]]
pattern = "${POSTMARK_API_DOMAIN:-api.postmarkapp.com}"
methods = ["POST"]
[activity_wasm.allowed_host.secrets]
env_vars = ["POSTMARK_SERVER_TOKEN"]
replace_in = ["headers"]
