build:

verify-local:
	obelisk deployment verify --allow-unavailable-runtime-config --deployment obelisk-local.toml

verify-oci:
	obelisk deployment verify --allow-unavailable-runtime-config --deployment obelisk-oci.toml

push tag:
	(../../scripts/push-components.sh {{ tag }})

serve:
	obelisk server run --deployment obelisk-local.toml
