[[activity_wasm]]
name = "activity_docker"
location = "oci://docker.io/getobelisk/components_docker_activity_docker:2026-02-12@sha256:f96011811edcefaaaa45c7599e80c7ffe0c7d80cea64a6c376b6b1853363d53c"
directories  = { enabled = true, process_provider = "native"}
