[[activity_wasm]]
name = "activity_docker"
location = "${DEPLOYMENT_DIR}/../../target/wasm32-wasip2/release_activity/activity_docker.wasm"
directories  = { enabled = true, process_provider = "native"}
