[[activity_wasm]]
name = "activity_sendgrid_email"
location = "${DEPLOYMENT_DIR}/../../target/wasm32-wasip2/release_activity/activity_sendgrid_email.wasm"
exec.lock_expiry.seconds = 30
env_vars = [{key="SENDGRID_API_URL", value="${SENDGRID_API_URL:-https://api.sendgrid.com/v3/mail/send}"}]
[[activity_wasm.allowed_host]]
pattern = "${SENDGRID_API_DOMAIN:-api.sendgrid.com}"
methods = ["POST"]
[activity_wasm.allowed_host.secrets]
env_vars = ["SENDGRID_API_KEY"]
replace_in = ["headers"]
