[[activity_wasm]]
name = "activity_openai_responses"
location = "target/wasm32-wasip2/release_activity/activity_openai_responses.wasm"
exec.lock_expiry.seconds = 60
env_vars = [{key="OPENAI_API_BASE_URL", value="${OPENAI_API_BASE_URL:-https://api.openai.com/v1}"}]
[[activity_wasm.allowed_host]]
pattern = "${OPENAI_API_DOMAIN:-api.openai.com}"
methods = ["POST", "GET", "DELETE"]
secrets = ["OPENAI_API_KEY"]
replace_in = ["headers"]
