[[activity_wasm]]
name = "activity_openai_responses"
location = "oci://docker.io/getobelisk/components_openai_activity_openai_responses:2026-03-30@sha256:29b922a7b1a6b0859c6e3b9b6cb2731c92e9d5c8c984cdccb14bc75c3512ae94"
exec.lock_expiry.seconds = 60
env_vars = [{key="OPENAI_API_BASE_URL", value="${OPENAI_API_BASE_URL:-https://api.openai.com/v1}"}]
[[activity_wasm.allowed_host]]
pattern = "${OPENAI_API_DOMAIN:-api.openai.com}"
methods = ["POST", "GET", "DELETE"]
[activity_wasm.allowed_host.secrets]
env_vars = ["OPENAI_API_KEY"]
replace_in = ["headers"]
