build:
	CARGO_TARGET_DIR=target cargo build --profile=release_activity

verify-local:
	obelisk deployment verify --server-config server.toml --allow-unavailable-runtime-config --deployment obelisk-local.toml

verify-oci:
	obelisk deployment verify --server-config server.toml --allow-unavailable-runtime-config --deployment obelisk-oci.toml

push tag:
	(../../scripts/push-components.sh {{ tag }})

serve:
	obelisk server run --server-config server.toml --deployment obelisk-local.toml
