build:
	cargo build --profile=release_activity

verify-local:
	obelisk server verify --ignore-missing-env-vars -c obelisk-local.toml

verify-oci:
	obelisk server verify --ignore-missing-env-vars -c obelisk-oci.toml

push tag:
	(../../scripts/push-components.sh {{ tag }})

serve:
	obelisk server run -c obelisk-local.toml
