[[activity_wasm]]
name = "activity_fly_http"
location = "target/wasm32-wasip2/release_activity/activity_fly_http.wasm"
exec.lock_expiry.seconds = 15
[[activity_wasm.allowed_host]]
pattern = "https://api.machines.dev"
methods = "*"
[activity_wasm.allowed_host.secrets]
env_vars = ["FLY_API_TOKEN"]
replace_in = ["headers"]
