[[activity_wasm]]
name = "activity_github_graphql"
location = "${DEPLOYMENT_DIR}/../../target/wasm32-wasip2/release_activity/activity_github_graphql.wasm"
exec.lock_expiry.seconds = 5
[[activity_wasm.allowed_host]]
pattern = "https://api.github.com"
methods = ["POST"]
[activity_wasm.allowed_host.secrets]
env_vars = ["GITHUB_TOKEN"]
replace_in = ["headers"]
