[[activity_wasm]]
name = "activity_github_graphql"
location = "oci://docker.io/getobelisk/components_github_activity_github_graphql:2026-04-08@sha256:6bc07b77e908266ae5cc4f36c69ce2949bb714b420be9f111e09e90a5e9107d0"
exec.lock_expiry.seconds = 5
[[activity_wasm.allowed_host]]
pattern = "https://api.github.com"
methods = ["POST"]
[activity_wasm.allowed_host.secrets]
env_vars = ["GITHUB_TOKEN"]
replace_in = ["headers"]
