[[activity_wasm]]
name = "activity_github_graphql"
location = "oci://docker.io/getobelisk/components_github_activity_github_graphql:2026-03-30@sha256:9419f896a4a6da15d76c7181e7abbaee4289675bdb1234cc94d2eccb55c91a13"
exec.lock_expiry.seconds = 5
[[activity_wasm.allowed_host]]
pattern = "https://api.github.com"
methods = ["POST"]
[activity_wasm.allowed_host.secrets]
env_vars = ["GITHUB_TOKEN"]
replace_in = ["headers"]
