[[activity_wasm]]
name = "activity_github_graphql"
location = "oci://docker.io/getobelisk/components_github_activity_github_graphql:2026-02-12@sha256:5e98344f5aaf2c7ee759fbd4cd80784d9cb4aa3b90951c67a5a23f0d4ed38952"
exec.lock_expiry.seconds = 5
[[activity_wasm.allowed_host]]
pattern = "https://api.github.com"
methods = ["POST"]
[activity_wasm.allowed_host.secrets]
env_vars = ["GITHUB_TOKEN"]
replace_in = ["headers"]
