build:
	CARGO_TARGET_DIR=target cargo build --profile=release_webhook
verify-local:
	obelisk server verify --allow-unavailable-runtime-config --deployment obelisk-local.toml
verify-oci:
	obelisk server verify --allow-unavailable-runtime-config --deployment obelisk-oci.toml
push tag:
	(../../scripts/push-components.sh {{ tag }})
