[[webhook_endpoint_wasm]]
name = "webhook_fly_secrets_updater"
location = "target/wasm32-wasip2/release_webhook/webhook_fly_secrets_updater.wasm"
routes = [{ methods = ["POST"], route = "/" }]
[[webhook_endpoint_wasm.allowed_host]]
pattern = "https://api.machines.dev"
methods = ["POST"]
[webhook_endpoint_wasm.allowed_host.secrets]
env_vars = ["FLY_API_TOKEN"]
replace_in = ["headers"]
