[[webhook_endpoint_wasm]]
name = "webhook_fly_secrets_updater"
location = "oci://docker.io/getobelisk/components_fly_webhook_fly_secrets_updater:2026-07-13@sha256:94ad43260a6621456888bdf2c56735c8cc054eb87506b549ddf19725aa463c5e"
routes = [{ methods = ["POST"], route = "/" }]
[[webhook_endpoint_wasm.allowed_host]]
pattern = "https://api.machines.dev"
methods = ["POST"]
secrets = ["FLY_API_TOKEN"]
replace_in = ["headers"]
